# minimal config for fuzzing — psk-only ikev2 policy
user "user1" "password123"
ikev2 esp \
    from 10.3.0.0/24 to 10.1.0.0/24 \
    local 192.168.1.1 peer 192.168.2.1 \
    psk "you-should-not-use-psk-authentication!"
